version: 2.1

references:
  container_config: &container_config
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:11-jdk
    working_directory: ~/repo

  environment_config: &environment_config
    environment:
      # Customize the JVM maximum heap limit:
      # -Xmx3200m

      # Suppress info about downloads:
      # -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN

      # Still execute the other tests even if one fails:
      # --fail-at-end

      # Show error messages:
      # --errors

      # Tell maven to not wait for user input:
      # --batch-mode

      MAVEN_OPTS: "-Xmx3200m -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN"
      MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end"

commands:
  prepare_maven:
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      # Resolve dependencies
      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

  save_surefire:
    steps:
      - run:
          name: Save test results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/junit/ \;
          when: always
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit

jobs:
  build:
    description: Build
    <<: *container_config
    <<: *environment_config
    steps:
      - prepare_maven
      - run: echo $MAVEN_CLI_OPTS
      - run: mvn $MAVEN_CLI_OPTS clean test-compile

  test:
    description: Unit tests
    <<: *container_config
    <<: *environment_config
    steps:
      - prepare_maven
      - run: mvn $MAVEN_CLI_OPTS test
      - save_surefire

  integration_test:
    description: Integration tests
    <<: *container_config
    <<: *environment_config
    steps:
      - prepare_maven
      - run: mvn $MAVEN_CLI_OPTS verify -Pintegration-test
      - save_surefire

  acceptance_test:
    description: Acceptance tests
    <<: *container_config
    <<: *environment_config
    steps:
      - prepare_maven
      - run: mvn $MAVEN_CLI_OPTS verify -Pacceptance-test
      - save_surefire

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - integration_test:
          requires:
            - build
      - acceptance_test:
          requires:
            - build